@SERVER=http://localhost:8000

GET {{SERVER}}


### register
POST http://localhost:8000/api/register
content-type: application/json

{
 "firstname": "edson",
 "lastname": "chauke",
 "email": "edson@gmail.com",
 "password":"123456"
}



### login
POST http://localhost:8000/api/login
content-type: application/json

{
"email": "edson@gmail.com",
 "password":"123456"
}


###create
POST http://localhost:8000/api/add
content-type: application/json

{
  "name": "nike",
 "number":"2 tops"
}
 