@SERVER=http://localhost:2000

GET {{SERVER}}


### register
POST http://localhost:2000/api/register
content-type: application/json

{
 "firstname": "aaaaa",
 "lastname": "aaaaaa",
 "email": "a@a.a",
 "password":"123456"
}



### login
POST http://localhost:2000/api/login
content-type: application/json

{
"email": "a@a.a",
 "password":"123456"
}


###create
POST http://localhost:2000/api/create
content-type: application/json

{
  "name": "nike",
 "number":"2"
}

###Update 

PUT http://localhost:2000/api/items/656ebd9b120c5e72d9af672d
content-type: application/json

{

  "name": "Adidas", 
  "number": "4 top"
  
 }

#####read


GET http://localhost:2000/api/items


### delete
DELETE http://localhost:2000/api/items/65718c110a987ee0bb89ebe1
content-type: application/json

{
"email": "edson@gmail.com",
 "password":"123456"
}